services:
  mxnet1.3.0gluon0.3.0gpu_learngluon:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: mxnet1.3.0gluoncv0.3.0:gpu
    volumes:
    - .:/app
    - nvidia_driver_384.130:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.130:
    external: true
